import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

export interface ConversationMessage {
  text: string;
  fromMe?: boolean;
  timestamp?: string;
}

export async function generateReply(
  conversationHistory: ConversationMessage[],
  recipientName: string
): Promise<string> {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY not configured in environment');
  }

  if (conversationHistory.length === 0) {
    throw new Error('No conversation history provided');
  }

  try {
    // Use the latest available models from v1 API
    // Available: gemini-2.5-flash, gemini-2.5-pro, gemini-2.0-flash
    const model = genAI.getGenerativeModel({
      model: 'gemini-2.5-flash'  // Fastest and most efficient
    });

    const conversationText = conversationHistory
      .map(msg => {
        const sender = msg.fromMe ? 'You' : recipientName;
        const time = msg.timestamp ? ` (${msg.timestamp})` : '';
        return `${sender}${time}: ${msg.text}`;
      })
      .join('\n\n');

    const prompt = `You are helping compose a professional LinkedIn message reply to ${recipientName}.

Here is the conversation history:
${conversationText}

Based on this conversation, generate a professional, concise, and contextually appropriate reply. Guidelines:
- Keep it professional and friendly
- Address any questions or points raised in the last message
- Keep the response under 200 words
- Match the tone of the conversation
- Don't repeat information already discussed
- Be natural and conversational
- Do NOT sign the message (no "Best regards", "Sincerely", name, or signature)
- Do NOT add greetings if continuing an ongoing conversation

Generate only the message text, without any labels, formatting, or signature:`;

    const result = await model.generateContent(prompt);
    const response = result.response;
    const text = response.text();

    // Add AI-generated prefix
    return `*** Generated by AI (ignore) ***\n\n${text.trim()}`;
  } catch (error: any) {
    if (error?.message?.includes('API_KEY_INVALID')) {
      throw new Error('Invalid Gemini API key');
    }
    if (error?.message?.includes('QUOTA_EXCEEDED')) {
      throw new Error('Gemini API quota exceeded. Try again later.');
    }

    console.error('[AI Service] Gemini error:', error);
    throw new Error('Failed to generate AI reply: ' + (error?.message || 'Unknown error'));
  }
}
